# WhatATheme
markdown: kramdown

# URL of the Site
url: 'wwtenantcommunity.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: WW Tenant Community Council Site
# Description of the Site
description: website for the WWTC mostly for doc repo n stuff
# URL of Image of the Site
site-image: /assets/commisstren.png
# Keywords of the Site
site-keywords: wild, woods, tenants, community, council, democracy, transparency, rage against the machine
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: wwtenantcommunity@gmail.com
facebook_username: Wildwoods of Lake Johnson (Tenant Union Council)
#twitter_username: thedevslot
#instagram_username: thedevslot
#linkedin_username: thedevslot
github_username:  thedevslot
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
#disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot (theme), DallHoff (other crap)
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# sum41 Words About the Author
author-about: --The quick brown fox jumps over the lazy dog-- is actually a sentence that uses all the letters of the alphabet.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://gonnaleavethisoutforthetimebeing.mk

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
